# evaluation configuration used in evalutate.py and partially in gui.py

device: 'cuda'
torch-seed: 0
snapshot-dir: './runs/{}/snapshots'

models:
  runs: ['maxout-0.1-full-final', 'mcnnt-0.1-full-final']
  model-names: ['mcnnTMax', 'mcnnT']
  model-versions: ['best', 'best']
  aggregation-types: ['bilinear', 'bilinear']

gui:
  evalutate-at-start: true
  baseline-run: 'mcnnt-baseline-final2'
  baseline-model-name: 'mcnnT'
  baseline-model-version: 'best'

# only available for mcnnNoisy and onwards
se2-noise:
  enable: false
  se2-noise-theta-std: 3.0 # degrees
  se2-noise-dx-std: 0.4    # meters
  se2-noise-dy-std: 0.4    # meters

plot:
  count: 10
  plot-type: 'disk' # 'show' || 'image' for getting rgb
  plot-dir: './runs/{}/plots'
  plot-tag: 'nostats' # added to dir name

curriculum:
  difficulty: 1
  maximum-agent-count: 8

dataset:
  random-samples: false
  classes: 'ours'
  output-h: 256
  output-w: 205
  dataset-dir: '/export/home/aiscar4/mass-data'
  dataset-file: 'noisy_towns1.hdf5'
  dataset-name: 'validation_set'