device: 'cuda'
run: 'bigbi-67-ce'

model:
  model-name: 'mcnnL'
  model-version: 'best' # || 'best'
  aggregation-type: 'bilinear' # or 'nearest'
  average-aggregation: false
  aggregation-activation-limit: 1e-6

plot:
  count: 10
  plot-type: 'disk' # 'show' || 'image' for getting rgb
  plot-dir: './runs/{}/plots'
  plot-tag: 'nostats' # added to dir name

dataset:
  difficulty: 1
  random-samples: false
  dataset-split: 'test'