# evaluation configuration used in evalutate.py and partially in gui.py

device: 'cuda'
torch-seed: 0
snapshot-dir: './runs/{}/snapshots'

models:
  runs: ['drop-0.1-full-deconv']
  model-names: ['mcnnT']
  model-versions: ['best']
  aggregation-types: ['bilinear']

gui:
  baseline-run: 'baseline-deconv'
  baseline-model-name: 'mcnnT'
  baseline-model-version: 'best'

plot:
  count: 10
  plot-type: 'disk' # 'show' || 'image' for getting rgb
  plot-dir: './runs/{}/plots'
  plot-tag: 'nostats' # added to dir name

curriculum:
  difficulty: 1
  maximum-agent-count: 8

dataset:
  random-samples: false
  classes: 'ours'
  output-h: 256
  output-w: 205
  dataset-dir: '/export/home/aiscar4/mass-data'
  dataset-file: 'towns_5.hdf5'
  dataset-name: 'validation_set'