# evaluation configuration used in evalutate.py and partially in gui.py

device: 'cuda'
torch-seed: 0
snapshot-dir: './runs/{}/snapshots'

models:
  runs: ['mcnnt2x-nodrop-ce-baseline', 'mcnnT3xNoisy-[4-.6-.6]-ce-0.1']
  graph-networks: [false, true]
  model-names: ['mcnnT2x', 'mcnnT3xNoisy']
  model-versions: ['best', 'best']
  aggregation-types: ['bilinear', 'bilinear']

gui:
  evalutate-at-start: true
  mask-threshold: 0.6

# only tackled in mcnnNoisy and onwards
se2-noise:
  se2-noise-theta-std: 3.0 # degrees
  se2-noise-dx-std: 0.4    # meters
  se2-noise-dy-std: 0.4    # meters

dataset:
  random-samples: false
  classes: 'ours'
  output-h: 256
  output-w: 205
  gaussian-blur-std: 0.0
  gaussian-kernel-size: 11
  dataset-dir: '/export/home/aiscar4/mass-data'
  dataset-file: 'noisy_towns1.hdf5'
  dataset-name: 'validation_set'

curriculum:
  difficulty: 8
  maximum-agent-count: 8

plot:
  count: 10
  plot-type: 'disk' # 'show' || 'image' for getting rgb
  plot-dir: './runs/{}/plots'
  plot-tag: 'nostats' # added to dir name