# evaluation configuration used in evalutate.py and partially in gui.py

device: 'cuda'
run: 'last-no-avg-66'
torch-seed: 0
snapshot-dir: './runs/{}/snapshots'

model:
  model-name: 'mcnnLW'
  model-version: 'last' # || 'best'
  aggregation-type: 'bilinear' # or 'nearest'

plot:
  count: 10
  plot-type: 'disk' # 'show' || 'image' for getting rgb
  plot-dir: './runs/{}/plots'
  plot-tag: 'nostats' # added to dir name

curriculum:
  difficulty: 1
  maximum-agent-count: 8

dataset:
  random-samples: false
  classes: 'ours'
  output-h: 256
  output-w: 205
  dataset-split: 'test'
  dataset-dir: '/export/home/aiscar4/mass-data'
  dataset-file: 'dataset_10k.hdf5'
  dataset-name: 'town-01'