# evaluation configuration used in evalutate.py and partially in gui.py

device: 'cuda'
torch-seed: 0
snapshot-dir: './runs/{}/snapshots'

models:
  extra-arg: './runs/mcnnT3x-ce-0.1-uniform-math/snapshots/best_model.pth'
  runs: [
         'mcnnT3xNoisyRT-coolnoise-nodrop-mse-unidata',
         'mcnnT3x-ce-0.1-unidata-[4-.6-.6]-2xaggr+post'
        ]
  graph-networks: [
                   true,
                   true,
                  ]
  model-names: [
                'mcnnT3xNoisyRT',
                'mcnnT3x',
               ]
  model-versions: [
                   'best',
                   'best',
                  ]
  aggregation-types: [
                      'bilinear',
                      'bilinear',
                     ]

gui:
  evaluate-noise-at-start: false
  evaluate-ious-at-start: false
  profile-at-start: false
  sample-save-dir: './samples'
  full-metrics-save-dir: '.'
  mask-threshold: 0.6
  transparent-masks: True

# only tackled in mcnnT3xNoisyRT
se2-noise:
  se2-noise-theta-std: 4.0 # degrees
  se2-noise-dx-std: 0.6    # meters
  se2-noise-dy-std: 0.6    # meters

dataset:
  random-samples: false
  classes: 'ours'
  output-h: 256
  output-w: 205
  gaussian-blur-std: 0.0
  gaussian-kernel-size: 11
  dataset-dir: '/export/home/aiscar4/mass-data'
  dataset-file: 'noisy_town1_uniform.hdf5'
  dataset-name: 'validation_set'

curriculum:
  difficulty: 8
  maximum-agent-count: 8

plot:
  count: 10
  plot-type: 'disk' # 'show' || 'image' for getting rgb
  plot-dir: './runs/{}/plots'
  plot-tag: 'nostats' # added to dir name