dataset:
  dataset-dir: '/export/home/bahadorm/mass-data'
  dataset-file: 'dataset_10k.hdf5'
  dataset-name: 'town-01'

logging:
  name: 'debug'
  log-dir: './log'
  log-every: 10 # batch
  snapshot-dir: './runs/{}/snapshots'

training:
  device: 'cuda'
  torch-seed: 0
  distributed: false
  world-size: 2
  loss: 'cross-entropy' # 'focal'
  weight-losses: false

dataloader:
  pin-memory: false
  dataloder-workers: 1
  shuffle-data: true

network:
  model-name: 'mcnn'
  norm-keep-stats: false # instance norm

curriculum:
  initial-difficulty: 1
  maximum-difficulty: 1
  maximum-agent-count: 8
  strategy: 'every-x-epochs'
  strategy-parameter: 500


hyperparameters:
  learning-rate: 5e-3
  epochs: 500
  # probability that an agent stops transmitting
  drop-prob: 0.0
  output-h: 256
  output-w: 205
  classes: 'ours'
  num-classes: 7

validation:
  # threshold for counting the mask pixel as detected
  mask-det-threshold: 0.6

evaluation:
  dataset: 'test'
  run: 'newviz-FOC'
  model-name: 'mcnn'
  batchnorm-keep-stats: true
  model-version: 'last' # || 'best'
  random-samples: true
  count: 50
  plot: 'disk' # 'show' || 'image' for getting rgb
  plot-dir: './runs/{}/plots'
  plot-tag: 'nostats' # added to dir name
  difficulty: 1
