logging:
  name: 'baseline-deconv'
  group: 'moderate'
  log-dir: './log'
  log-every: 10 # batch
  snapshot-dir: './runs/{}/snapshots'

training:
  device: 'cuda'
  torch-seed: 0
  loss: 'cross-entropy' # or 'focal'
  weight-losses: true

network:
  model-name: 'mcnnT'
  aggregation-type: 'bilinear' # or 'nearest'

resume:
  flag: false
  tag: 'resume'
  decoder-only: false
  resume-optimizer-state: true
  starting-epoch: 11
  difficulty: 8
  model-version: 'best'

curriculum:
  activate: false
  initial-difficulty: 1
  maximum-difficulty: 1
  maximum-agent-count: 8
  strategy: 'metric'
  strategy-parameter: 0.66

hyperparameters:
  learning-rate: 5e-3
  epochs: 500
  # probability that an agent stops transmitting
  drop-prob: 0.0
  # brightness, contrast, saturation, hue
  color-jitter: [0.2, 0.2, 0.2, 0.2]

validation:
  # threshold for counting the mask pixel as detected
  mask-det-threshold: 0.6

dataloader:
  dataloder-workers: 1
  shuffle-data: true

dataset:
  output-h: 256
  output-w: 205
  classes: 'ours'
  num-classes: 7
  dataset-dir: '/export/home/bahadorm/mass-data'
  trainset-file: 'towns_1234.hdf5'
  trainset-name: 'training_set'
  validset-file: 'towns_5.hdf5'
  validset-name: 'validation_set'