dataset:
  dataset-dir: '/export/home/bahadorm/mass-data'
  dataset-file: 'dataset_10k.hdf5'
  dataset-name: 'town-01'

logging:
  name: 'newviz-CE'
  log-dir: './log'
  log-every: 10 # batch
  snapshot-dir: './runs/{}/snapshots'

training:
  device: 'cuda'
  torch-seed: 0
  distributed: false
  world-size: 2

dataloader:
  pin-memory: false
  dataloder-workers: 1
  shuffle-data: true

curriculum:
  initial-difficulty: 1
  maximum-difficulty: 1
  maximum-agent-count: 8
  strategy: 'every-x-epochs'
  strategy-parameter: 100

hyperparameters:
  learning-rate: 5e-3
  epochs: 500
  # probability that an agent stops transmitting
  drop-prob: 0.0
  output-h: 256
  output-w: 205
  classes: 'ours'
  num-classes: 7
  model-size: 'large'
  loss: 'cross-entropy' # 'focal'

validation:
  # threshold for counting the mask pixel as detected
  mask-det-threshold: 0.6

evaluation:
  dataset: 'test'
  run: 'wishful-thiking-focal'
  model: 'last' # or 'last'
  random-samples: true
  count: 100
  plot: 'disk' # or 'show'
  plot-dir: './runs/{}/plots'
  difficulty: 1
