logging:
  name: 'debug'
  group: 'moderate'
  log-dir: './log'
  log-every: 10 # batch
  snapshot-dir: './runs/{}/snapshots'

training:
  device: 'cuda'
  torch-seed: 10
  loss: 'weighted-cross-entropy'
  ce-weights: [5.7101e+00, 5.2976e+00, 5.8594e-02, 4.1832e-01, 1.0000e+00, 5.6783e-01, 2.0297e+02]

# currently only tackled in mcnnNoisy
se2-noise:
  enable: false
  se2-noise-theta-std: 4.0 # degrees
  se2-noise-dx-std: 0.6    # meters
  se2-noise-dy-std: 0.6    # meters

network:
  model-name: 'mcnnT4x'
  aggregation-type: 'bilinear'

hyperparameters:
  learning-rate: 1e-4
  epochs: 500
  # probability that an agent stops transmitting
  drop-prob: 0.1
  # brightness, contrast, saturation, hue
  color-jitter: [0.1, 0.1, 0.1, 0.1]

validation:
  # threshold for counting the mask pixel as detected
  mask-det-threshold: 0.6

dataloader:
  dataloder-workers: 1
  shuffle-data: true

dataset:
  output-h: 256
  output-w: 205
  classes: 'ours' # carla, ours, ours+mask, diminished
  dataset-dir: '/export/home/aiscar4/mass-data'
  trainset-file: 'noisy_towns1.hdf5'
  trainset-name: 'validation_set'
  validset-file: 'noisy_towns1.hdf5'
  validset-name: 'validation_set'

curriculum:
  activate: false
  initial-difficulty: 8
  maximum-difficulty: 8
  maximum-agent-count: 8
  strategy: 'metric'
  strategy-parameter: 0.66

resume:
  flag: false
  tag: 'resume'
  resume-optimizer-state: true
  starting-epoch: 11
  difficulty: 8
  model-version: 'best'
