logging:
  name: 'debug'
  group: 'moderate'
  log-dir: './log'
  log-every: 10 # batch
  snapshot-dir: './runs/{}/snapshots'

training:
  device: 'cuda'
  torch-seed: 20
  loss: 'cross-entropy' # or 'cross-entropy'
  weight-losses: true

# only available for mcnnNoisy and onwards
se3-noise:
  enable: false
  se3-noise-theta-std: 2.0 # degrees
  se3-noise-dx-std: 0.5    # meters
  se3-noise-dy-std: 0.5    # meters

network:
  model-name: 'mcnnNoisy'
  aggregation-type: 'bilinear' # or 'nearest'

curriculum:
  activate: false
  initial-difficulty: 1
  maximum-difficulty: 1
  maximum-agent-count: 8
  strategy: 'metric'
  strategy-parameter: 0.66

hyperparameters:
  learning-rate: 5e-3
  epochs: 500
  # probability that an agent stops transmitting
  drop-prob: 0.0
  # brightness, contrast, saturation, hue
  color-jitter: [0.1, 0.1, 0.1, 0.1]

validation:
  # threshold for counting the mask pixel as detected
  mask-det-threshold: 0.6
  visualize-hard-batches: false
  hard-batch-indices: []

dataloader:
  dataloder-workers: 1
  shuffle-data: true

dataset:
  output-h: 256
  output-w: 205
  classes: 'ours' # carla, ours, diminished
  dataset-dir: '/export/home/aiscar4/mass-data'
  trainset-file: 'noisy_towns1.hdf5'
  trainset-name: 'validation_set'
  validset-file: 'noisy_towns1.hdf5'
  validset-name: 'validation_set'

resume:
  flag: false
  tag: 'resume'
  resume-optimizer-state: true
  starting-epoch: 11
  difficulty: 8
  model-version: 'best'
