logging:
  name: 'mcnnT3x-[4.|.6|.6]-ce-0.1'
  group: 'advanced'
  log-dir: './log'
  log-every: 10 # batch
  snapshot-dir: './runs/{}/snapshots'

training:
  device: 'cuda'
  torch-seed: 101
  loss: 'cross-entropy'
  ce-weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

# currently only tackled in mcnnT3xNoisy
se2-noise:
  enable: true
  se2-noise-theta-std: 4.0 # degrees
  se2-noise-dx-std: 0.6    # meters
  se2-noise-dy-std: 0.6    # meters

network:
  model-name: 'mcnnT3x'
  aggregation-type: 'bilinear'

hyperparameters:
  learning-rate: 1e-3
  epochs: 500
  # probability that an agent stops transmitting
  drop-prob: 0.1
  # brightness, contrast, saturation, hue
  color-jitter: [0.1, 0.1, 0.1, 0.1]
  # guassian smoothing of masks
  gaussian-blur-std: 0
  gaussian-kernel-size: 11
  # mask wallhack probability
  wallhack-prob: 0.0

validation:
  # threshold for counting the mask pixel as detected
  mask-det-threshold: 0.6

dataloader:
  dataloder-workers: 0
  shuffle-data: true

dataset:
  output-h: 256
  output-w: 205
  classes: 'ours' # carla, ours, ours+mask, diminished, diminished+mask
  dataset-dir: '/export/home/bahadorm/mass-data'
  trainset-file: 'noisy_towns2345.hdf5'
  trainset-name: 'training_set'
  validset-file: 'noisy_towns1.hdf5'
  validset-name: 'validation_set'

curriculum:
  activate: false
  initial-difficulty: 8
  maximum-difficulty: 8
  maximum-agent-count: 8
  enforce-max-calc: false
  strategy: 'metric'
  strategy-parameter: 0.66

resume:
  flag: true
  tag: 'resume'
  resume-optimizer-state: true
  starting-epoch: 12
  difficulty: 8
  model-version: 'last'