parameters:
  name: 'test'
  dataset-dir: '/export/home/bahadorm/mass-data'
  dataset-file: 'dataset_10k.hdf5'
  dataset-name: 'town-01'
  tensorboard-dir: './tensorboard'
  snapshot-dir: './snapshots'
  device: 'cuda'
  distributed: false # impossible for now


hyperparameters:
  # probability that an agent stops transmitting
  learning-rate: 1e-4
  epochs: 1000
  drop-prob: 0.0
  output-h: 256
  output-w: 205
  classes: 'ours'
  num-classes: 7
  model-size: 'large'
  loss: 'focal' # 'cross-entropy'

validation:
  # threshold for counting the mask pixel as detected
  mask-det-threshold: 0.6