logging:
  name: 'debug'
  group: 'advanced'
  log-dir: './log'
  log-every: 10 # batch
  snapshot-dir: './runs/{}/snapshots'

training:
  device: 'cuda'
  torch-seed: 10
  loss: 'cross-entropy'
  ce-weights: [9.7452e+01, 9.0411e+01, 1.0000e+00, 7.1393e+00, 1.7067e+01, 9.6910e+00, 3.4640e+03]

# currently only tackled in mcnnNoisy
se2-noise:
  enable: false
  se2-noise-theta-std: 4.0 # degrees
  se2-noise-dx-std: 0.6    # meters
  se2-noise-dy-std: 0.6    # meters

network:
  model-name: 'mcnnT2x'
  aggregation-type: 'bilinear'

hyperparameters:
  learning-rate: 1e-3
  epochs: 500
  # probability that an agent stops transmitting
  drop-prob: 0.0
  # brightness, contrast, saturation, hue
  color-jitter: [0.1, 0.1, 0.1, 0.1]
  # guassian smoothing of masks
  guassian-blur-std: 0.4
  guassian-kernel-size: 10
  # mask wallhack probability
  wallhack-prob: 0.4

validation:
  # threshold for counting the mask pixel as detected
  mask-det-threshold: 0.6

dataloader:
  dataloder-workers: 0
  shuffle-data: true

dataset:
  output-h: 256
  output-w: 205
  classes: 'ours' # carla, ours, ours+mask, diminished
  dataset-dir: '/export/home/aiscar4/mass-data'
  trainset-file: 'noisy_towns1.hdf5'
  trainset-name: 'validation_set'
  validset-file: 'noisy_towns1.hdf5'
  validset-name: 'validation_set'

curriculum:
  activate: false
  initial-difficulty: 8
  maximum-difficulty: 8
  maximum-agent-count: 8
  strategy: 'metric'
  strategy-parameter: 0.66

resume:
  flag: false
  tag: 'resume'
  resume-optimizer-state: true
  starting-epoch: 11
  difficulty: 8
  model-version: 'best'