dataset:
  dataset-dir: '/export/home/bahadorm/mass-data'
  dataset-file: 'dataset_10k.hdf5'
  dataset-name: 'town-01'

logging:
  name: 'comms-every-15'
  log-dir: './log'
  log-every: 5 # batch
  logger: 'wandb' # or tensorboard
  snapshot-dir: './snapshots'

training:
  device: 'cuda'
  torch-seed: 0
  distributed: false
  world-size: 2

dataloader:
  pin-memory: false
  dataloder-workers: 1
  shuffle-data: false

curriculum:
  initial-difficulty: 1
  maximum-difficulty: 8
  maximum-agent-count: 8
  strategy: 'every-x-epochs'
  strategy-parameter: 15

hyperparameters:
  # probability that an agent stops transmitting
  learning-rate: 1e-4
  epochs: 1000
  drop-prob: 0.0
  output-h: 256
  output-w: 205
  classes: 'ours'
  num-classes: 7
  model-size: 'large'
  loss: 'focal' # 'cross-entropy'

validation:
  # threshold for counting the mask pixel as detected
  mask-det-threshold: 0.6